{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "demochart.serviceAccountName" . }}-{{uuid4 }}
  labels:
{{ include "demochart.labels" . | nindent 4 }}
{{- end -}}
